<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "championshipmanager"
 *
 * Auto generated by Extension Builder 2015-04-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Championship Manager',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Berti Golf, Max Rosenmüller',
	'author_email' => 'berti@golf-net.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);